import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { ApolloClient, InMemoryCache, gql } from '@apollo/client';
import Card from '../components/Card';

export default function Home({ launches }) {
  return (
    <div className="container">
      <Head>
        <title>SpaceX Launches</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          <span>SpaceX</span> Launches
        </h1>

        <p className={styles.description}>Latest launched from SpaceX 🚀</p>

        <div className={styles.grid}>
          {launches.map((data,idx) => {
            return (
             <Card data={data} key={idx}/>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://api.spacex.land/graphql/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by <span>Next.JS + SpaceX API</span>
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: 'https://api.spacex.land/graphql',
    cache: new InMemoryCache(),
  });

  const { data } = await client.query({
    query: gql`
      query GetLaunches {
        launchesPast(limit: 10) {
          id
          mission_name
          launch_date_local
          launch_site {
            site_name_long
          }
          links {
            article_link
            video_link
            mission_patch
          }
          rocket {
            rocket_name
          }
        }
      }
    `,
  });
  return {
    props: {
      launches: data.launchesPast,
    },
  };
}
